//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HSFoxx.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HSFOXX_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_DLG_AA_PARAM                129
#define IDC_VIDEO                       1000
#define IDC_VIDEO6                      1000
#define IDC_PLAY                        1001
#define IDC_INFO                        1002
#define IDC_VIDEO0                      1002
#define IDC_LOAD                        1003
#define IDC_OSTEST                      1004
#define IDC_STARTAA                     1004
#define IDC_PLAY2                       1004
#define IDC_LIST1                       1005
#define IDC_OSEASY                      1006
#define IDC_SAVEPICTURE                 1007
#define IDC_SETPOWER                    1008
#define IDC_SAVEPICTURE3                1009
#define IDC_SETMCLK                     1009
#define IDC_EDIT1                       1010
#define IDC_EDITAVDD                    1010
#define IDC_EDIT1_Z                     1010
#define IDC_EDITDOVDD                   1011
#define IDC_EDIT3_Z                     1011
#define IDC_EDITDVDD                    1012
#define IDC_EDIT4_Z                     1012
#define IDC_EDITAFVCC                   1013
#define IDC_EDIT5_Z                     1013
#define IDC_EDITVPP                     1014
#define IDC_EDIT6_Z                     1014
#define IDC_SAVEPICTURE2                1015
#define IDC_TEST_ROI                    1015
#define IDC_EDIT7_Z                     1015
#define IDC_EDITMCLK                    1016
#define IDC_EDIT8_Z                     1016
#define IDC_TEST_ROI2                   1017
#define IDC_ENUM                        1017
#define IDC_EDIT9_Z                     1017
#define IDC_KITLIST                     1018
#define IDC_EDIT0_Z                     1018
#define IDC_EDIT2                       1019
#define IDC_AF_POS                      1019
#define IDC_EDIT2_Z                     1019
#define IDC_FOCUS_POS                   1020
#define IDC_EDITCOM                     1021
#define IDC_EDITCOMPORT                 1021
#define IDC_EDIT_ZADJUST                1021
#define IDC_VIDEO1                      1021
#define IDC_INITIALDEVICE               1022
#define IDC_EDIT_THRO                   1022
#define IDC_VIDEO2                      1022
#define IDC_PITLIST                     1023
#define IDC_EDIT1_UV                    1023
#define IDC_ENUMNETDEVICE               1024
#define IDC_EDIT3_UV                    1024
#define IDC_GOHOME                      1025
#define IDC_EDIT4_UV                    1025
#define IDC_INIT_X                      1026
#define IDC_STEP_X                      1026
#define IDC_EDIT5_UV                    1026
#define IDC_INIT_U                      1027
#define IDC_STEP_U                      1027
#define IDC_EDIT6_UV                    1027
#define IDC_INIT_Y                      1028
#define IDC_STEP_Y                      1028
#define IDC_EDIT7_UV                    1028
#define IDC_INIT_Z                      1029
#define IDC_STEP_Z                      1029
#define IDC_EDIT8_UV                    1029
#define IDC_INIT_V                      1030
#define IDC_STEP_V                      1030
#define IDC_EDIT9_UV                    1030
#define IDC_IDC_INIT_W                  1031
#define IDC_INIT_W                      1031
#define IDC_STEP_W                      1031
#define IDC_EDIT0_UV                    1031
#define IDC_CONNECT                     1032
#define IDC_EDIT2_UV                    1032
#define IDC_CURPOSITION                 1033
#define IDC_EDIT_UVADJUST               1033
#define IDC_CURX                        1034
#define IDC_EDIT_UVTHRO                 1034
#define IDC_CURU                        1035
#define IDC_CURY                        1036
#define IDC_CURZ                        1037
#define IDC_CURV                        1038
#define IDC_CURW                        1039
#define IDC_FZ                          1040
#define IDC_ZY                          1041
#define IDC_FY                          1042
#define IDC_ZX                          1043
#define IDC_FX                          1044
#define IDC_EDIT_scale                  1044
#define IDC_ZZ                          1045
#define IDC_EDIT_pic_length             1045
#define IDC_FW                          1046
#define IDC_EDIT_pixel_size             1046
#define IDC_ZV                          1047
#define IDC_EDIT_mapsize                1047
#define IDC_FV                          1048
#define IDC_EDIT_focus                  1048
#define IDC_ZU                          1049
#define IDC_EDIT_objdis                 1049
#define IDC_FU                          1050
#define IDC_EDIT_size                   1050
#define IDC_ZW                          1051
#define IDC_EDIT_edgesize               1051
#define IDC_MIDDIS                      1052
#define IDC_EDIT_mapdiswidth            1052
#define IDC_SHORTDIS                    1053
#define IDC_EDIT_block                  1053
#define IDC_LONGDIS                     1054
#define IDC_EDIT_pic_height             1054
#define IDC_EDIT_LOG                    1055
#define IDC_EDIT_mapdislength           1055
#define IDC_BTN_AAPARAM                 1056
#define IDC_EDIT_blocksize              1056
#define IDC_VIDEO7                      1057
#define IDC_EDIT_CHANNEL1               1057
#define IDC_PLAY_VISION0                1058
#define IDC_EDIT_CHANNEL2               1058
#define IDC_PLAY_VISION1                1059
#define IDC_EDIT_CHANNEL3               1059
#define IDC_PLAY_VISION2                1060
#define IDC_EDIT_CHANNEL4               1060
#define IDC_PLAY_VISION3                1061
#define IDC_EDIT_CHANNEL5               1061
#define IDC_PLAY_VISION4                1062
#define IDC_EDIT_CHANNEL6               1062
#define IDC_PLAY_VISION5                1063
#define IDC_EDIT_CHANNEL7               1063
#define IDC_PLAY_VISION6                1064
#define IDC_EDIT_CHANNEL8               1064
#define IDC_PLAY_VISION7                1065
#define IDC_EDIT_DOUBLESCALE            1065
#define IDC_VIDEO3                      1066
#define IDC_EDIT_DOUBLEDIS              1066
#define IDC_VIDEO4                      1067
#define IDC_EDIT_DOUBLEDISLENGTH        1067
#define IDC_VIDEO5                      1068
#define IDC_EDIT_DOUBLEDISWIHTH         1068
#define IDC_VIDEOFRME                   1069
#define IDC_EDIT_DOUBLESIZE             1069
#define IDC_CONNECTCLOSE                1070
#define IDC_TEST_TEST                   1071
#define IDC_EDIT_DOUBLECENTERX          1071
#define IDC_PICTURECENTER               1072
#define IDC_EDIT_DOUBLECENTERY          1072
#define IDC_READPIC_TEST                1073
#define IDC_EDIT_DOUBLECENTERY2         1073
#define IDC_EDIT_DOUBLECENTHRES         1073
#define IDC_BEIZHU                      1074
#define IDC_SETINITPOS                  1074
#define IDC_PI_HOME                     1075
#define IDC_PI_HOME1                    1076
#define IDC_SETINITPOS1                 1077
#define IDC_SIGTYPE                     1077
#define IDC_DOUTYPE                     1078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
